"""
心理学基础数据和常量定义
用于提供Few-shot examples和参考框架
"""

from models import PsychologicalIssue, TherapyApproach, CounselorState, EmotionState


# ==================== 心理问题数据库 ====================
# 用于背景生成Agent的参考和Few-shot examples

PSYCHOLOGICAL_ISSUES_DATA = {
    PsychologicalIssue.ACADEMIC_ANXIETY: {
        "name": "学业焦虑",
        "description": "对学习成绩、考试、学业表现的过度担心和焦虑",
        "common_symptoms": [
            "考试前紧张失眠",
            "担心成绩不好",
            "学习压力大",
            "注意力难以集中",
            "总觉得时间不够",
            "害怕老师提问",
            "看到成绩就紧张",
            "复习时心慌",
            "觉得自己不够聪明",
        ],
        "student_expressions": [
            "我一想到考试就睡不着觉",
            "感觉压力好大，喘不过气",
            "总觉得自己学得不够好",
            "看到别人学习就焦虑",
            "害怕让父母失望",
            "不敢看考试成绩",
        ],
    },
    PsychologicalIssue.SOCIAL_PHOBIA: {
        "name": "社交恐惧",
        "description": "在社交场合感到强烈恐惧和不安，回避人际交往",
        "common_symptoms": [
            "害怕与人交流",
            "在人群中感到不适",
            "担心被人评判",
            "脸红心跳",
            "声音发抖",
            "回避社交活动",
            "不敢主动说话",
            "担心说错话",
            "觉得别人在议论自己",
        ],
        "student_expressions": [
            "我不敢在课堂上发言",
            "和陌生人说话就紧张",
            "总觉得别人在看我",
            "参加聚会很难受",
            "不知道怎么和同学聊天",
            "害怕被拒绝",
        ],
    },
    PsychologicalIssue.DEPRESSION: {
        "name": "抑郁情绪",
        "description": "持续的情绪低落、兴趣丧失、自我价值感降低",
        "common_symptoms": [
            "情绪低落",
            "对事情失去兴趣",
            "觉得自己很糟糕",
            "容易疲倦",
            "睡眠问题",
            "食欲变化",
            "注意力下降",
            "自责自罪",
            "觉得未来没希望",
        ],
        "student_expressions": [
            "最近总是很难过",
            "什么都不想做",
            "觉得自己很失败",
            "每天都很累",
            "对未来感到迷茫",
            "觉得活着没意思",
        ],
    },
    PsychologicalIssue.PROCRASTINATION: {
        "name": "拖延症",
        "description": "习惯性地推迟或避免完成任务，导致焦虑和压力",
        "common_symptoms": [
            "总是拖到最后一刻",
            "明知道要做却不行动",
            "为拖延感到内疚",
            "时间管理困难",
            "容易分心",
            "逃避重要任务",
            "deadline前焦虑",
            "自我批评",
            "完美主义倾向",
        ],
        "student_expressions": [
            "我总是拖作业到最后",
            "明知道该学习但就是不想动",
            "时间总是不够用",
            "一想到要做就烦躁",
            "总是被其他事情分心",
            "每次都说明天开始",
        ],
    },
    PsychologicalIssue.OCD_SYMPTOMS: {
        "name": "强迫症状",
        "description": "反复出现不必要的想法或行为，难以控制",
        "common_symptoms": [
            "反复检查",
            "重复某些动作",
            "强迫性思维",
            "过度清洁",
            "需要对称或完美",
            "反复确认",
            "害怕出错",
            "仪式化行为",
            "如果不做就焦虑",
        ],
        "student_expressions": [
            "我总是要检查好多遍",
            "门锁了没有要确认很多次",
            "东西必须放得整整齐齐",
            "总有些想法挥之不去",
            "如果不按顺序做就觉得不对",
            "洗手要洗很久",
        ],
    },
    PsychologicalIssue.ADAPTATION_ISSUES: {
        "name": "适应性问题",
        "description": "对新环境、新角色、新变化的适应困难",
        "common_symptoms": [
            "难以适应新环境",
            "想念以前的生活",
            "角色转换困难",
            "社交圈建立困难",
            "生活习惯改变",
            "文化差异适应",
            "独立生活压力",
            "离家焦虑",
            "新规则学习困难",
        ],
        "student_expressions": [
            "我还是想回家",
            "这里的生活不习惯",
            "感觉格格不入",
            "想念高中的朋友",
            "不知道怎么安排大学生活",
            "一个人生活好困难",
        ],
    },
    PsychologicalIssue.RELATIONSHIP_ISSUES: {
        "name": "恋爱情感问题",
        "description": "恋爱关系中的困扰、分手创伤、情感依赖等问题",
        "common_symptoms": [
            "恋爱关系冲突",
            "分手痛苦",
            "情感依赖",
            "嫉妒心理",
            "缺乏安全感",
            "沟通困难",
            "期望过高",
            "害怕被抛弃",
            "情绪波动大",
        ],
        "student_expressions": [
            "我和男/女朋友总是吵架",
            "分手后很痛苦",
            "总是担心对方不爱我了",
            "不知道怎么处理感情",
            "觉得自己不够好",
            "害怕再次受伤",
        ],
    },
    PsychologicalIssue.FAMILY_CONFLICTS: {
        "name": "家庭关系问题",
        "description": "与家人的冲突、沟通障碍、价值观差异等问题",
        "common_symptoms": [
            "与父母观念冲突",
            "沟通不畅",
            "感到不被理解",
            "家庭压力大",
            "期望过高",
            "代际差异",
            "控制与独立矛盾",
            "经济依赖焦虑",
            "家庭责任压力",
        ],
        "student_expressions": [
            "父母总是管得太多",
            "他们不理解我的想法",
            "家里压力很大",
            "总是被拿来和别人比较",
            "想要独立但又依赖家里",
            "和家人很难沟通",
        ],
    },
    PsychologicalIssue.IDENTITY_CONFUSION: {
        "name": "自我认同困惑",
        "description": "对自己的价值观、能力、未来方向感到困惑",
        "common_symptoms": [
            "不知道自己想要什么",
            "专业选择迷茫",
            "未来规划困难",
            "自我价值不确定",
            "能力怀疑",
            "兴趣不明确",
            "人生方向迷失",
            "角色认同困惑",
            "存在意义质疑",
        ],
        "student_expressions": [
            "我不知道自己适合做什么",
            "对专业没有兴趣",
            "不知道毕业后要干什么",
            "觉得自己很迷茫",
            "不确定自己的能力",
            "人生没有方向感",
        ],
    },
    PsychologicalIssue.SLEEP_PROBLEMS: {
        "name": "睡眠问题",
        "description": "入睡困难、睡眠质量差、作息紊乱等睡眠障碍",
        "common_symptoms": [
            "难以入睡",
            "睡眠浅易醒",
            "早醒",
            "作息不规律",
            "白天困倦",
            "噩梦频繁",
            "睡前焦虑",
            "睡眠时间不足",
            "睡眠质量差",
        ],
        "student_expressions": [
            "我总是睡不着",
            "躺在床上脑子停不下来",
            "半夜总是醒",
            "白天很困但晚上精神",
            "睡眠质量很差",
            "总是做噩梦",
        ],
    },
}


# ==================== 咨询流派数据库 ====================
# 用于咨询师Bot的system prompt构建和背景生成

THERAPY_APPROACHES_DATA = {
    TherapyApproach.CBT: {
        "name": "认知行为疗法",
        "description": "关注认知、情绪和行为之间的关系，通过改变不合理认知来改善情绪和行为",
        "key_techniques": [
            "认知重构",
            "行为实验",
            "问题解决训练",
            "放松训练",
            "暴露疗法",
            "认知日记",
            "家庭作业布置",
        ],
        "communication_style": [
            "结构化询问",
            "引导式提问",
            "关注具体事件",
            "挑战不合理想法",
            "布置实践任务",
            "关注此时此地",
        ],
        "typical_questions": [
            "你觉得这种想法合理吗？",
            "有什么证据支持这个想法？",
            "你能想到其他的解释吗？",
            "如果朋友遇到同样情况，你会怎么建议？",
        ],
    },
    TherapyApproach.HUMANISTIC: {
        "name": "人本主义疗法",
        "description": "强调人的自我实现潜能，通过无条件积极关注和共情来促进成长",
        "key_techniques": [
            "积极关注",
            "共情反映",
            "真诚一致",
            "情感反映",
            "澄清技术",
            "开放式提问",
            "支持与鼓励",
        ],
        "communication_style": [
            "温暖接纳",
            "非指导性",
            "关注感受",
            "反映情感",
            "避免建议",
            "相信来访者能力",
        ],
        "typical_questions": [
            "听起来你感到很...",
            "我能感受到你的...",
            "你刚才提到的感受对你来说意味着什么？",
            "你觉得什么对你最重要？",
        ],
    },
    TherapyApproach.PSYCHOANALYTIC: {
        "name": "精神分析取向",
        "description": "探索无意识动机和早期经历对现在行为的影响",
        "key_techniques": [
            "自由联想",
            "梦的分析",
            "移情分析",
            "阻抗分析",
            "解释技术",
            "童年经历探索",
            "无意识探索",
        ],
        "communication_style": [
            "深层探索",
            "关注过去",
            "解释行为动机",
            "分析防御机制",
            "探索潜意识",
            "关注象征意义",
        ],
        "typical_questions": [
            "这让你想到了什么？",
            "你童年时是否有过类似经历？",
            "你觉得这种反应背后可能有什么原因？",
            "这种感觉熟悉吗？",
        ],
    },
    TherapyApproach.SOLUTION_FOCUSED: {
        "name": "解决焦点疗法",
        "description": "关注解决方案而非问题本身，寻找来访者的优势和资源",
        "key_techniques": [
            "例外探索",
            "资源发掘",
            "目标设定",
            "奇迹问题",
            "评量问题",
            "赞美技术",
            "小步骤改变",
        ],
        "communication_style": [
            "关注解决方案",
            "寻找例外",
            "发掘优势",
            "具体目标导向",
            "简短高效",
            "正向关注",
        ],
        "typical_questions": [
            "什么时候这个问题没有发生？",
            "你是怎么做到的？",
            "如果明天醒来问题解决了，你会注意到什么不同？",
            "你希望达到什么目标？",
        ],
    },
    TherapyApproach.MINDFULNESS: {
        "name": "正念疗法",
        "description": "通过正念练习提高觉察能力，接纳当下体验",
        "key_techniques": [
            "正念冥想",
            "身体扫描",
            "呼吸觉察",
            "接纳练习",
            "观察思维",
            "情绪调节",
            "当下体验",
        ],
        "communication_style": [
            "引导觉察",
            "关注当下",
            "接纳态度",
            "体验式学习",
            "非评判性",
            "温和引导",
        ],
        "typical_questions": [
            "现在你感受到了什么？",
            "注意一下你的呼吸...",
            "让我们觉察一下当下的感受",
            "你能接纳这种感觉吗？",
        ],
    },
}


# ==================== 状态转换参考信息 ====================
# 用于流程控制Agent判断状态转换

STATE_TRANSITION_GUIDE = {
    CounselorState.INTRODUCTION: {
        "entry_condition": "对话开始",
        "exit_condition": "建立初步信任关系，了解基本问题",
        "key_goals": ["建立关系", "创造安全氛围", "初步了解问题"],
        "typical_duration": "3-6轮",
        "transition_indicators": [
            "学生开始主动分享",
            "语气变得放松",
            "愿意描述具体情况",
            "对咨询师表现出信任",
            "开始询问咨询相关问题",
        ],
        "minimum_rounds": 3,
    },
    CounselorState.EXPLORATION: {
        "entry_condition": "学生开始信任，愿意分享更多信息",
        "exit_condition": "对核心问题有了全面深入的了解",
        "key_goals": ["深入探索", "系统收集信息", "保持情感支持"],
        "typical_duration": "4-6轮",
        "transition_indicators": [
            "核心信息已收集充分",
            "学生情绪状态稳定",
            "问题脉络清晰",
            "咨询师已形成初步判断",
            "学生准备接受专业反馈",
        ],
        "minimum_rounds": 4,
    },
    CounselorState.ASSESSMENT: {
        "entry_condition": "信息收集充分，可以进行专业判断",
        "exit_condition": "形成初步诊断，学生理解和接受",
        "key_goals": ["整合信息", "专业判断", "初步诊断"],
        "typical_duration": "2-3轮",
        "transition_indicators": [
            "学生接受了初步诊断",
            "理解了问题的专业解释",
            "准备进行进一步评估",
            "询问下一步安排",
        ],
        "minimum_rounds": 2,
    },
    CounselorState.SCALE_RECOMMENDATION: {
        "entry_condition": "完成初步诊断，需要进一步评估",
        "exit_condition": "推荐合适的量表工具",
        "key_goals": ["推荐量表", "解释意义", "后续安排"],
        "typical_duration": "2-3轮",
        "transition_indicators": ["对话自然结束", "学生理解量表用途", "安排了后续评估"],
        "minimum_rounds": 2,
    },
}

EMOTION_TRANSITIONS = {
    EmotionState.ANXIOUS: [
        EmotionState.CALM,
        EmotionState.TRUSTING,
        EmotionState.HOPEFUL,
    ],
    EmotionState.DEPRESSED: [
        EmotionState.CALM,
        EmotionState.HOPEFUL,
        EmotionState.OPEN,
    ],
    EmotionState.CONFUSED: [
        EmotionState.CALM,
        EmotionState.OPEN,
        EmotionState.TRUSTING,
    ],
    EmotionState.ANGRY: [EmotionState.CALM, EmotionState.OPEN, EmotionState.RESISTANT],
    EmotionState.RESISTANT: [
        EmotionState.TRUSTING,
        EmotionState.OPEN,
        EmotionState.CALM,
    ],
    EmotionState.AVOIDANT: [
        EmotionState.OPEN,
        EmotionState.TRUSTING,
        EmotionState.CALM,
    ],
    EmotionState.CALM: [EmotionState.OPEN, EmotionState.TRUSTING, EmotionState.HOPEFUL],
    EmotionState.OPEN: [EmotionState.TRUSTING, EmotionState.HOPEFUL, EmotionState.CALM],
    EmotionState.TRUSTING: [EmotionState.HOPEFUL, EmotionState.OPEN, EmotionState.CALM],
    EmotionState.HOPEFUL: [EmotionState.CALM, EmotionState.TRUSTING, EmotionState.OPEN],
    EmotionState.OTHER: [EmotionState.CALM, EmotionState.OPEN, EmotionState.TRUSTING],
}


COMMON_MAJORS = [
    "计算机科学与技术",
    "软件工程",
    "信息管理与信息系统",
    "电子信息工程",
    "机械工程",
    "土木工程",
    "建筑学",
    "电气工程及其自动化",
    "工商管理",
    "市场营销",
    "财务管理",
    "人力资源管理",
    "会计学",
    "法学",
    "新闻学",
    "广告学",
    "汉语言文学",
    "英语",
    "心理学",
    "教育学",
    "社会工作",
    "政治学与行政学",
    "数学与应用数学",
    "物理学",
    "化学",
    "生物科学",
    "临床医学",
    "护理学",
    "药学",
    "中医学",
    "美术学",
    "音乐学",
    "设计学",
    "体育教育",
]

COMMON_GRADES = ["大一", "大二", "大三", "大四", "研一", "研二", "研三"]

COMMON_FAMILY_BACKGROUNDS = [
    "单亲家庭",
    "重组家庭",
    "普通双职工家庭",
    "农村家庭",
    "城市中产家庭",
    "留守儿童背景",
    "独生子女",
    "多子女家庭",
    "隔代抚养",
    "经济困难家庭",
]

COMMON_PERSONALITY_TRAITS = [
    "内向",
    "外向",
    "敏感",
    "理性",
    "情绪化",
    "完美主义",
    "乐观",
    "悲观",
    "独立",
    "依赖",
    "社交恐惧",
    "人来疯",
    "责任心强",
    "拖延",
    "焦虑型",
    "回避型",
    "安全型",
    "冲动",
    "谨慎",
    "创新",
    "保守",
    "竞争性强",
]

APPROACH_SPECIFIC_GUIDANCE = {
    TherapyApproach.CBT: {
        "introduction": "注重了解具体问题和症状，询问问题的具体表现",
        "exploration": "探索认知、情绪、行为之间的关系，关注具体情境",
        "assessment": "从认知行为角度分析问题，识别不合理认知",
        "scale": "推荐认知行为相关的量表和评估工具",
    },
    TherapyApproach.HUMANISTIC: {
        "introduction": "强调接纳和理解，创造安全无评判的环境",
        "exploration": "关注来访者的主观体验和感受，多用反映技术",
        "assessment": "以来访者的自我理解为主，避免过多专业诊断",
        "scale": "谨慎推荐量表，强调量表只是辅助工具",
    },
    TherapyApproach.PSYCHOANALYTIC: {
        "introduction": "营造分析性环境，鼓励自由表达",
        "exploration": "探索潜意识动机和早期经历的影响",
        "assessment": "从心理动力学角度理解问题，关注防御机制",
        "scale": "可能推荐投射测验或深层心理评估",
    },
    TherapyApproach.SOLUTION_FOCUSED: {
        "introduction": "快速建立合作关系，关注来访者的优势",
        "exploration": "寻找例外情况和已有的解决资源",
        "assessment": "关注解决方案而非问题分析，设定具体目标",
        "scale": "推荐目标达成度评估相关工具",
    },
    TherapyApproach.MINDFULNESS: {
        "introduction": "引导觉察当下体验，建立觉察的态度",
        "exploration": "探索身心体验，关注觉察能力",
        "assessment": "从正念觉察角度理解问题，强调接纳",
        "scale": "推荐正念水平评估量表",
    },
}
